[package]
name = "rust_bitcoin_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_bitcoin_lib"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniscript = "10.0.0"
